baseurl = "https://example.com/"
title = "Polisen"
languageCode = "en-us"

# Pagination
paginate = 3
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap"

[taxonomies]
  category = "categories"

# Google analytics
googleAnalytics = "UA-47268287-3"

# Languages

defaultContentLanguage = "en"

[languages.en]
  languageName = "English"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

# Links format

[permalinks]
  post = "/:year/:month/:title/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "John Doe"

  # Date format (default: Jan 2, 2006)
  date_format = "2006-01-02"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  [params.sidebar]
    # Weather to show the recent posts or not (default: true)
    # showRecent = false

    # Weather to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5